seed_phrase = "annual buffalo diagram mercy van pair size noise clap general ensure marble"
address = "GAIM4S6HDNGDW4R7452E3SGOSZ3UOAXXGHXEILCDRS4U7KZHRQAMJVOZ"
private_key = "SCZDIOL6BKV2RWYM7M2ORWSFGB3DYMNJ55EBDLNVIH2HJ3DQ4TMZPSOO"